const QRCode = require('qrcode');
const axios  = require('axios');

// qr | attp | stealemoji | type
module.exports = [
  {
    name: ['qr', 'qrcode', 'generateqr'],
    category: 'sick',
    description: 'Generate a QR code from any text or URL',
    usage: 'qr <text or URL>',
    async execute({ sock, msg, from, text, config }) {
      if (!text) return msg.reply(`❓ Usage: ${config.prefix}qr <text or URL>`);
      await msg.reply('⬛ _Generating QR code..._');
      try {
        const buf = await QRCode.toBuffer(text, { width: 512, margin: 2, color: { dark: '#000000', light: '#ffffff' } });
        await sock.sendMessage(from, { image: buf, caption: `⬛ *QR Code for:* ${text.slice(0, 60)}\n\n_Generated by Venom MD 🐍_` }, { quoted: msg });
      } catch (err) {
        await msg.reply(`❌ Error: ${err.message}`);
      }
    },
  },
  {
    name: ['attp', 'animatedtext', 'textgif'],
    category: 'sick',
    description: 'Make animated text sticker',
    usage: 'attp <text>',
    async execute({ sock, msg, from, text, config }) {
      if (!text) return msg.reply(`❓ Usage: ${config.prefix}attp <text>`);
      await msg.reply('🎨 _Creating animated sticker..._');
      try {
        const res = await axios.get(
          `https://api.siputzx.my.id/api/maker/attp?text=${encodeURIComponent(text)}`,
          { responseType: 'arraybuffer', timeout: 30000 }
        );
        await sock.sendMessage(from, { sticker: Buffer.from(res.data) }, { quoted: msg });
      } catch (err) {
        await msg.reply(`❌ Error: ${err.message}\n_Try simpler/shorter text._`);
      }
    },
  },
  {
    name: ['ttf', 'texttoimage', 'tti'],
    category: 'sick',
    description: 'Render styled text as an image',
    usage: 'ttf <text>',
    async execute({ sock, msg, from, text, config }) {
      if (!text) return msg.reply(`❓ Usage: ${config.prefix}ttf <text>`);
      await msg.reply('🖼️ _Rendering text..._');
      try {
        const res = await axios.get(
          `https://api.siputzx.my.id/api/maker/ttp?text=${encodeURIComponent(text)}`,
          { responseType: 'arraybuffer', timeout: 30000 }
        );
        await sock.sendMessage(from, { image: Buffer.from(res.data), caption: `✏️ ${text}` }, { quoted: msg });
      } catch (err) {
        await msg.reply(`❌ Error: ${err.message}`);
      }
    },
  },
  {
    name: ['ship', 'lovecalc', 'compatible'],
    category: 'sick',
    description: 'Calculate love compatibility between two users',
    usage: 'ship @user1 @user2',
    async execute({ sock, msg, from, args, config }) {
      const targets = msg.mentionedJid;
      if (!targets || targets.length < 2) {
        return msg.reply(`❓ Usage: ${config.prefix}ship @user1 @user2`);
      }
      const [a, b] = targets;
      const score  = Math.floor(Math.random() * 101);
      const bar    = '█'.repeat(Math.floor(score / 10)) + '░'.repeat(10 - Math.floor(score / 10));
      const emoji  = score >= 80 ? '💕' : score >= 50 ? '💛' : score >= 30 ? '😐' : '💔';
      await sock.sendMessage(from, {
        text:
          `${emoji} *Love Calculator*\n\n` +
          `👤 @${a.split('@')[0]}\n💗 &  💗\n👤 @${b.split('@')[0]}\n\n` +
          `*${bar}* ${score}%\n\n` +
          `_${score >= 80 ? 'Perfect match! 💍' : score >= 50 ? 'Good chemistry! 💛' : score >= 30 ? 'Meh... 😐' : 'This won\'t work 💔'}_`,
        mentions: targets,
      }, { quoted: msg });
    },
  },
];
